In [34]:
import pandas as pd

In [35]:
import numpy as np

In [36]:
df=pd.read_csv('KAG_energydata_complete.csv')

In [37]:
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [38]:
df.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [39]:
df.drop(['date', 'lights'], axis=1, inplace=True)

In [40]:
df.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,60,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,50,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,50,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,60,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [41]:
df1=pd.read_csv('train.csv')

In [42]:
df1.head()

,Observation,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,Energy
0,1111,22.700000,37.200,21.000000,38.000000,23.390000,37.290000,22.832857,34.942857,20.500000,...,45.360000,20.20,38.663333,12.80,760.050000,62.000000,3.5,28.0,5.65,70
1,1112,21.500000,41.045,20.500000,39.133333,22.926667,39.526667,21.700000,34.126667,18.633333,...,34.663333,19.73,37.933333,8.47,764.166667,48.166667,8.0,26.5,-1.92,210
2,1113,21.666667,38.000,22.600000,35.700000,21.890000,36.590000,22.000000,35.530000,19.000000,...,38.545000,19.79,39.430000,10.60,757.600000,57.000000,2.0,27.0,2.40,50
3,1114,23.290000,38.530,21.671429,38.000000,24.290000,36.200000,23.100000,35.090000,22.042857,...,38.600000,22.60,36.194286,11.60,760.600000,63.000000,1.0,40.0,4.67,50
4,1115,24.000000,42.560,26.830000,34.356000,26.530000,40.333333,24.500000,40.900000,21.500000,...,44.230000,22.60,44.090000,17.70,756.983333,63.000000,1.0,21.5,10.40,250

In [43]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15780 entries, 0 to 15779
Data columns (total 26 columns):
Observation    15780 non-null int64
T1             15780 non-null float64
RH_1           15780 non-null float64
T2             15780 non-null float64
RH_2           15780 non-null float64
T3             15780 non-null float64
RH_3           15780 non-null float64
T4             15780 non-null float64
RH_4           15780 non-null float64
T5             15780 non-null float64
RH_5           15780 non-null float64
T6             15780 non-null float64
RH_6           15780 non-null float64
T7             15780 non-null float64
RH_7           15780 non-null float64
T8             15780 non-null float64
RH_8           15780 non-null float64
T9             15780 non-null float64
RH_9           15780 non-null float64
T_out          15780 non-null float64
Press_mm_hg    15780 non-null float64
RH_out         15780 non-null float64
Windspeed      15780 non-null float64
Visibility     15780 non-null float64
Tdewpoint      15780 non-null float64
Energy         15780 non-null int64
dtypes: float64(24), int64(2)
memory usage: 3.1 MB

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 27 columns):
Appliances     19735 non-null int64
T1             19735 non-null float64
RH_1           19735 non-null float64
T2             19735 non-null float64
RH_2           19735 non-null float64
T3             19735 non-null float64
RH_3           19735 non-null float64
T4             19735 non-null float64
RH_4           19735 non-null float64
T5             19735 non-null float64
RH_5           19735 non-null float64
T6             19735 non-null float64
RH_6           19735 non-null float64
T7             19735 non-null float64
RH_7           19735 non-null float64
T8             19735 non-null float64
RH_8           19735 non-null float64
T9             19735 non-null float64
RH_9           19735 non-null float64
T_out          19735 non-null float64
Press_mm_hg    19735 non-null float64
RH_out         19735 non-null float64
Windspeed      19735 non-null float64
Visibility     19735 non-null float64
Tdewpoint      19735 non-null float64
rv1            19735 non-null float64
rv2            19735 non-null float64
dtypes: float64(26), int64(1)
memory usage: 4.1 MB

In [45]:
df1.columns

Index(['Observation', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4',
       'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9',
       'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility',
       'Tdewpoint', 'Energy'],
      dtype='object')

In [46]:
df.drop(['rv1', 'rv2'], inplace=True, axis=1)

In [47]:
df.columns

Index(['Appliances', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4',
       'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9',
       'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility',
       'Tdewpoint'],
      dtype='object')

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 25 columns):
Appliances     19735 non-null int64
T1             19735 non-null float64
RH_1           19735 non-null float64
T2             19735 non-null float64
RH_2           19735 non-null float64
T3             19735 non-null float64
RH_3           19735 non-null float64
T4             19735 non-null float64
RH_4           19735 non-null float64
T5             19735 non-null float64
RH_5           19735 non-null float64
T6             19735 non-null float64
RH_6           19735 non-null float64
T7             19735 non-null float64
RH_7           19735 non-null float64
T8             19735 non-null float64
RH_8           19735 non-null float64
T9             19735 non-null float64
RH_9           19735 non-null float64
T_out          19735 non-null float64
Press_mm_hg    19735 non-null float64
RH_out         19735 non-null float64
Windspeed      19735 non-null float64
Visibility     19735 non-null float64
Tdewpoint      19735 non-null float64
dtypes: float64(24), int64(1)
memory usage: 3.8 MB

In [49]:
df['Observation']=0
length=df['Observation'].count()

In [50]:
length

19735

In [51]:
for i in range(0,length+1):
    df['Observation'][i]=1111+i

C:\Users\Sandeep Yadav\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [53]:
df

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,Observation
0,60,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,17.166667,...,48.900000,17.033333,45.530000,6.600000,733.500000,92.000000,7.000000,63.000000,5.300000,1111
1,60,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,17.166667,...,48.863333,17.066667,45.560000,6.483333,733.600000,92.000000,6.666667,59.166667,5.200000,1112
2,50,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,17.166667,...,48.730000,17.000000,45.500000,6.366667,733.700000,92.000000,6.333333,55.333333,5.100000,1113
3,50,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,17.166667,...,48.590000,17.000000,45.400000,6.250000,733.800000,92.000000,6.000000,51.500000,5.000000,1114
4,60,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,17.200000,...,48.590000,17.000000,45.400000,6.133333,733.900000,92.000000,5.666667,47.666667,4.900000,1115
5,50,19.890000,46.026667,19.200000,44.500000,19.790000,44.933333,18.890000,45.730000,17.133333,...,48.590000,17.000000,45.290000,6.016667,734.000000,92.000000,5.333333,43.833333,4.800000,1116
6,60,19.890000,45.766667,19.200000,44.500000,19.790000,44.900000,18.890000,45.790000,17.100000,...,48.590000,17.000000,45.290000,5.900000,734.100000,92.000000,5.000000,40.000000,4.700000,1117
7,60,19.856667,45.560000,19.200000,44.500000,19.730000,44.900000,18.890000,45.863333,17.100000,...,48.590000,17.000000,45.290000,5.916667,734.166667,91.833333,5.166667,40.000000,4.683333,1118
8,60,19.790000,45.597500,19.200000,44.433333,19.730000,44.790000,18.890000,45.790000,17.166667,...,48.590000,17.000000,45.290000,5.933333,734.233333,91.666667,5.333333,40.000000,4.666667,1119
9,70,19.856667,46.090000,19.230000,44.400000,19.790000,44.863333,18.890000,46.096667,17.100000,...,48.590000,17.000000,45.290000,5.950000,734.300000,91.500000,5.500000,40.000000,4.650000,1120
10,230,19.926667,45.863333,19.356667,44.400000,19.790000,44.900000,18.890000,46.430000,17.100000,...,48.590000,17.000000,45.290000,5.966667,734.366667,91.333333,5.666667,40.000000,4.633333,1121
11,580,20.066667,46.396667,19.426667,44.400000,19.790000,44.826667,19.000000,46.430000,17.100000,...,48.633333,16.890000,45.290000,5.983333,734.433333,91.166667,5.833333,40.000000,4.616667,1122
12,430,20.133333,48.000000,19.566667,44.400000,19.890000,44.900000,19.000000,46.363333,17.100000,...,48.560000,16.963333,45.290000,6.000000,734.500000,91.000000,6.000000,40.000000,4.600000,1123
13,250,20.260000,52.726667,19.730000,45.100000,19.890000,45.493333,19.000000,47.223333,17.100000,...,48.666667,16.890000,45.326667,6.000000,734.616667,90.500000,6.000000,40.000000,4.516667,1124
14,100,20.426667,55.893333,19.856667,45.833333,20.033333,47.526667,19.000000,48.696667,17.100000,...,49.193333,16.890000,45.345000,6.000000,734.733333,90.000000,6.000000,40.000000,4.433333,1125
15,100,20.566667,53.893333,20.033333,46.756667,20.100000,48.466667,19.000000,48.490000,17.150000,...,49.200000,16.890000,45.326667,6.000000,734.850000,89.500000,6.000000,40.000000,4.350000,1126
16,90,20.730000,52.660000,20.166667,47.223333,20.200000,48.530000,18.926667,48.156667,17.166667,...,49.633333,16.890000,45.290000,6.000000,734.966667,89.000000,6.000000,40.000000,4.266667,1127
17,70,20.856667,53.660000,20.200000,47.056667,20.200000,48.447500,18.890000,47.963333,17.200000,...,50.026667,16.890000,45.290000,6.000000,735.083333,88.500000,6.000000,40.000000,4.183333,1128
18,80,20.890000,51.193333,20.200000,46.330000,20.200000,48.193333,18.963333,48.630000,17.200000,...,50.200000,16.890000,45.200000,6.000000,735.200000,88.000000,6.000000,40.000000,4.100000,1129
19,140,20.890000,49.800000,20.200000,46.026667,20.166667,47.633333,19.033333,49.500000,17.593333,...,50.260000,16.890000,45.200000,6.000000,735.233333,87.833333,6.000000,40.000000,4.066667,1130
20,120,20.890000,48.433333,20.200000,45.722500,20.166667,47.300000,19.175000,49.947500,18.066667,...,50.230000,16.890000,45.126667,6.000000,735.266667,87.666667,6.000000,40.000000,4.033333,1131
21,190,20.963333,47.633333,20.260000,45.530000,20.200000,47.026667,19.260000,49.696667,17.666667,...,50.290000,16.890000,45.126667,6.000000,735.300000,87.500000,6.000000,40.000000,4.000000,1132
22,110,21.033333,47.063333,20.290000,45.223333,20.260000,46.826667,19.323333,49.166667,17.600000,...,50.163333,16.890000,45.060000,6.000000,735.333333,87.333333,6.000000,40.000000,3.966667,1133
23,110,21.100000,46.596667,20.356667,44.963333,20.290000,46.633333,19.390000,48.426667,17.566667,...,50.030000,16.890000,45.000000,6.000000,735.366667,87.166667,6.000000,40.000000,3.933333,1134
24,110,21.133333,46.060000,20.426667,44.760000,20.290000,46.433333,19.390000,48.193333,17.760000,...,49.760000,16.890000,44.966667,6.000000,735.400000,87.000000,6.000000,40.000000,3.900000,1135
25,110,21.200000,45.800000,20.500000,44.760000,20.390000,46.223333,19.390000,47.800000,18.356667,...,49.700000,16.890000,44.900000,5.933333,735.466667,87.166667,6.000000,40.000000,3.866667,1136
26,100,21.290000,45.900000,20.533333,45.090000,20.390000,46.090000,19.390000,47.560000,18.356667,...,49.633333,16.890000,44.790000,5.866667,735.533333,87.333333,6.000000,40.000000,3.833333,1137
27,100,21.356667,45.826667,20.666667,45.163333,20.390000,46.090000,19.390000,47.500000,18.600000,...,49.433333,16.890000,44.790000,5.800000,735.600000,87.500000,6.000000,40.000000,3.800000,1138
28,100,21.390000,45.690000,20.700000,45.060000,20.390000,46.090000,19.426667,47.993333,18.666667,...,49.400000,16.890000,44.700000,5.733333,735.666667,87.666667,6.000000,40.000000,3.766667,1139
29,100,21.500000,45.333333,20.700000,44.933333,20.390000,46.060000,19.566667,48.466667,18.823333,...,49.326667,16.890000,44.700000,5.666667,735.733333,87.833333,6.000000,40.000000,3.733333,1140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19705,280,25.033333,48.363333,26.528571,40.595714,28.496667,41.900000,24.500000,45.066667,22.760000,...,49.090000,23.100000,46.500000,21.250000,756.050000,59.833333,1.166667,23.666667,13.100000,20816
19706,240,25.166667,48.156667,26.600000,40.940000,28.290000,41.966667,24.500000,45.333333,22.790000,...,49.163333,23.100000,46.500000,21.400000,756.000000,59.666667,1.333333,23.333333,13.200000,20817
19707,250,25.323333,47.930000,26.600000,41.012857,28.200000,42.090000,24.533333,45.566667,22.790000,...,49.290000,23.100000,46.522500,21.550000,755.950000,59.500000,1.500000,23.000000,13.300000,20818
19708,220,25.390000,47.656667,26.600000,41.036000,28.200000,42.030000,24.600000,45.760000,22.790000,...,49.290000,23.100000,46.530000,21.700000,755.900000,59.333333,1.666667,22.666667,13.400000,20819
19709,230,25.500000,47.133333,26.600000,41.000000,28.200000,41.796667,24.600000,45.790000,22.856667,...,49.326667,23.100000,46.530000,21.850000,755.850000,59.166667,1.833333,22.333333,13.500000,20820
19710,190,25.500000,47.060000,26.540000,41.000000,28.200000,41.530000,24.600000,45.863333,22.890000,...,49.326667,23.100000,46.530000,22.000000,755.800000,59.000000,2.000000,22.000000,13.600000,20821
19711,160,25.600000,46.990000,26.512500,41.203750,28.200000,41.590000,24.633333,46.030000,22.890000,...,49.345000,23.100000,46.530000,21.966667,755.800000,59.000000,2.000000,21.833333,13.550000,20822
19712,80,25.600000,46.730000,26.437143,41.384286,28.426667,41.430000,24.700000,46.090000,22.890000,...,49.326667,23.100000,46.590000,21.933333,755.800000,59.000000,2.000000,21.666667,13.500000,20823
19713,60,25.566667,46.633333,26.370000,41.378000,28.566667,41.156667,24.700000,45.966667,22.890000,...,49.326667,23.100000,46.626667,21.900000,755.800000,59.000000,2.000000,21.500000,13.450000,20824
19714,60,25.500000,46.360000,26.318571,41.264286,28.566667,40.663333,24.700000,45.826667,22.890000,...,49.163333,23.100000,46.700000,21.866667,755.800000,59.000000,2.000000,21.333333,13.400000,20825
19715,60,25.500000,46.060000,26.350000,41.000000,28.426667,40.590000,24.666667,45.526667,22.890000,...,49.030000,23.100000,46.590000,21.833333,755.800000,59.000000,2.000000,21.166667,13.350000,20826
19716,60,25.500000,45.933333,26.277143,41.000000,28.356667,40.560000,24.666667,45.400000,22.945000,...,49.000000,23.100000,46.590000,21.800000,755.800000,59.000000,2.000000,21.000000,13.300000,20827
19717,70,25.500000,45.760000,26.200000,41.000000,28.290000,40.433333,24.700000,45.363333,23.000000,...,49.000000,23.133333,46.590000,21.966667,755.750000,58.333333,2.000000,21.333333,13.283333,20828
19718,80,25.500000,45.626667,26.171429,41.000000,28.260000,40.260000,24.700000,45.230000,23.000000,...,48.790000,23.133333,46.590000,22.133333,755.700000,57.666667,2.000000,21.666667,13.266667,20829
19719,80,25.500000,45.590000,26.100000,41.000000,28.200000,40.126667,24.700000,45.163333,23.033333,...,48.790000,23.166667,46.590000,22.300000,755.650000,57.000000,2.000000,22.000000,13.250000,20830
19720,70,25.500000,45.522500,26.100000,41.051429,28.200000,40.200000,24.700000,45.163333,23.033333,...,48.790000,23.100000,46.590000,22.466667,755.600000,56.333333,2.000000,22.333333,13.233333,20831
19721,100,25.500000,45.633333,26.080000,41.196000,28.133333,40.260000,24.700000,45.300000,23.033333,...,48.930000,23.200000,46.590000,22.633333,755.550000,55.666667,2.000000,22.666667,13.216667,20832
19722,100,25.500000,45.730000,26.000000,41.428571,28.100000,40.433333,24.700000,45.433333,23.100000,...,49.456667,23.200000,46.590000,22.800000,755.500000,55.000000,2.000000,23.000000,13.200000,20833
19723,90,25.500000,45.790000,26.000000,41.590000,28.100000,40.560000,24.700000,45.500000,23.100000,...,50.076000,23.160000,46.590000,22.833333,755.450000,55.000000,2.166667,22.833333,13.233333,20834
19724,100,25.500000,45.933333,26.000000,41.652857,28.000000,40.700000,24.700000,45.466667,23.100000,...,50.716000,23.200000,46.621429,22.866667,755.400000,55.000000,2.333333,22.666667,13.266667,20835
19725,220,25.426667,46.060000,26.000000,41.700000,28.000000,40.760000,24.700000,45.400000,23.200000,...,51.333333,23.200000,46.700000,22.900000,755.350000,55.000000,2.500000,22.500000,13.300000,20836
19726,180,25.500000,46.530000,26.000000,41.725714,27.856667,40.500000,24.700000,45.500000,23.200000,...,51.632000,23.200000,46.652857,22.933333,755.300000,55.000000,2.666667,22.333333,13.333333,20837
19727,120,25.500000,47.456667,26.000000,42.320000,27.663333,40.693333,24.700000,45.560000,23.200000,...,51.500000,23.200000,46.718000,22.966667,755.250000,55.000000,2.833333,22.166667,13.366667,20838
19728,110,25.600000,47.193333,25.968571,42.528571,27.390000,41.030000,24.700000,45.626667,23.200000,...,50.863333,23.200000,46.751429,23.000000,755.200000,55.000000,3.000000,22.000000,13.400000,20839
19729,90,25.533333,46.860000,25.978000,42.534000,27.323333,41.090000,24.700000,45.626667,23.200000,...,50.445000,23.200000,46.745000,22.866667,755.200000,55.333333,3.166667,22.833333,13.366667,20840
19730,100,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,23.200000,...,50.074000,23.200000,46.790000,22.733333,755.200000,55.666667,3.333333,23.666667,13.333333,20841
19731,90,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,45.590000,23.230000,...,49.790000,23.200000,46.790000,22.600000,755.200000,56.000000,3.500000,24.500000,13.300000,20842
19732,270,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,23.230000,...,49.660000,23.200000,46.790000,22.466667,755.200000,56.333333,3.666667,25.333333,13.266667,20843
19733,420,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,23.200000,...,49.518750,23.200000,46.817500,22.333333,755.200000,56.666667,3.833333,26.166667,13.233333,20844
19734,430,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,23.200000,...,49.736000,23.200000,46.845000,22.200000,755.200000,57.000000,4.000000,27.000000,13.200000,20845

In [54]:
from sklearn.ensemble import RandomForestRegressor

In [61]:
rfg=RandomForestRegressor(n_estimators=275,max_features='log2')

In [62]:
df.columns

Index(['Appliances', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4',
       'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9',
       'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility',
       'Tdewpoint', 'Observation'],
      dtype='object')

In [63]:
X_train=df.drop('Appliances', axis=1)

In [64]:
Y_train=df['Appliances']

In [65]:
rfg.fit(X_train, Y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='log2', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=275, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [71]:
test_data=pd.read_csv('test.csv')

In [76]:
predictions=rfg.predict(test_data)

In [77]:
from sklearn.model_selection import GridSearchCV

In [78]:
param = {
                     'n_estimators': [200,250,300],
                     'max_features': ['sqrt', 'auto', 'log2']           
        }
model = GridSearchCV(RandomForestRegressor(),param,verbose=True,n_jobs=-1)

In [79]:
model.fit(X_train, Y_train)

Fitting 3 folds for each of 9 candidates, totalling 27 fits

[Parallel(n_jobs=-1)]: Done  27 out of  27 | elapsed:  8.8min finished

GridSearchCV(cv=None, error_score='raise',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'n_estimators': [200, 250, 300], 'max_features': ['sqrt', 'auto', 'log2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=True)